hide empty members

class Persona {
    id
}

abstract class PersonaPersona  {
    id
}

PersonaPersona <|-- PersonaPersonaFísica
PersonaPersona <|-- PersonaPersonaJurídica

Persona *- "1" PersonaPersona : persona

Persona *-- "*" PersonaCategoría : categorías
Persona *-- "*" PersonaImpuesto : impuestos
Persona *-- "*" PersonaDomicilio : domicilios
Persona *-- "*" PersonaTeléfono : teléfonos
Persona *-- "*" PersonaEmail : emails
Persona *-- "*" PersonaJurisdicción : jurisdicciones
Persona *-- "*" PersonaActividad : actividades
Persona *-- "*" PersonaContribuciónMunicipal : contrimunis
Persona *-- "*" PersonaArchivo : archivos
Persona *-- "*" PersonaEtiqueta : etiquetas
Persona *-- "*" PersonaRelación : relaciones
Persona *-- "*" PersonaSedeConvenioMultilateral : cmsedes

PersonaCategoría -[hidden]-- PersonaImpuesto
PersonaImpuesto -[hidden]-- PersonaDomicilio
PersonaDomicilio -[hidden]-- PersonaTeléfono
PersonaTeléfono -[hidden]-- PersonaEmail
PersonaEmail -[hidden]-- PersonaJurisdicción
PersonaJurisdicción -[hidden]-- PersonaActividad
PersonaActividad -[hidden]-- PersonaContribuciónMunicipal
PersonaContribuciónMunicipal -[hidden]-- PersonaArchivo
PersonaArchivo -[hidden]-- PersonaEtiqueta
PersonaEtiqueta -[hidden]-- PersonaRelación
PersonaRelación -[hidden]-- PersonaSedeConvenioMultilateral
